---
language: python
python: "3.6"

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install tox

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
