---

- name: Add authorized keys
  authorized_key:
    user: "{{ item.0.key }}"
    key: '{{ lookup("file", item.1) }}'
    state: present
  with_subelements:
    - "{{ authorized_keys_present |dict2items }}"
    - "value"
